{application, calc, 
 [{description, "a calculator"}, 
  {vsn, "0.1.0"}, 
  {modules, [calc_app, 
             calc_sup,
			 calcgui,
			 calc,
			 calc_server,
			 calc_store]}, 
  {registered, [calc_sup]}, 
  {applications, [kernel, stdlib]}, 
  {mod, {calc_app, []}}]}. 